services:
  mysql:
    image: mysql:8.3
    restart: always
    container_name: local-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: localdb
      MYSQL_USER: dev
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
